import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'architecture',
    {
      type: 'category',
      label: 'Getting Started',
      items: ['getting-started/installation', 'getting-started/quickstart'],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/index',
        'tutorials/customer-support-bot',
        'tutorials/document-qa',
        'tutorials/research-agent',
        'tutorials/hitl-workflow',
        'tutorials/cost-aware-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/rag',
        'concepts/agents',
        'concepts/graphs',
        'concepts/embeddings',
      ],
    },
    {
      type: 'category',
      label: 'RAG',
      items: [
        'rag/pipeline',
        'rag/loaders',
        'rag/splitter',
        'rag/retriever',
        'rag/vector-stores',
        'rag/parsers',
        'rag/prompts',
        'rag/prompt-hub',
      ],
    },
    {
      type: 'category',
      label: 'LLMs',
      items: [
        'llms/overview',
        'llms/openai',
        'llms/anthropic',
        'llms/ollama',
        'llms/cohere',
        'llms/mistral',
        'llms/gemini',
        'llms/bedrock',
        'llms/azure-openai',
        'llms/groq',
        'llms/deepseek',
        'llms/openrouter',
        'llms/together',
        'llms/fireworks',
        'llms/perplexity',
        'llms/cerebras',
        'llms/vertex-ai',
        'llms/caching-retries',
        'llms/cost-router',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      items: [
        'agents/overview',
        'agents/react',
        'agents/function-calling',
        'agents/tools',
        'agents/executor',
        'agents/mcp',
        'agents/cookbook',
        'agents/tool-authoring',
        'agents/streaming-steps',
      ],
    },
    {
      type: 'category',
      label: 'Multi-Agent',
      items: ['multi-agent/overview', 'multi-agent/a2a'],
    },
    {
      type: 'category',
      label: 'Evaluation',
      items: ['evaluation/overview'],
    },
    {
      type: 'category',
      label: 'Guardrails',
      items: ['guardrails/overview'],
    },
    {
      type: 'category',
      label: 'Observability',
      items: ['observability/overview', 'observability/cost-tracker', 'observability/audit-log'],
    },
    {
      type: 'category',
      label: 'Multimodal',
      items: ['multimodal/overview'],
    },
    {
      type: 'category',
      label: 'Graph Workflows',
      items: [
        'graph/overview',
        'graph/state-graph',
        'graph/nodes',
        'graph/edges',
        'graph/compiled-graph',
        'graph/cycles',
        'graph/checkpointing',
        'graph/mermaid',
      ],
    },
    {
      type: 'category',
      label: 'CLI',
      items: ['cli/overview', 'cli/serve', 'cli/test'],
    },
    'plugins',
    {
      type: 'category',
      label: 'Memory & Tracing',
      items: ['memory/conversation', 'memory/token-tracer'],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      items: [
        'how-to/index',
        'how-to/streaming',
        'how-to/custom-llm-provider',
        'how-to/custom-tools',
        'how-to/custom-retrievers',
        'how-to/memory',
        'how-to/error-handling',
        'how-to/testing',
        'how-to/production',
        'how-to/migrate-from-langchain',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/llm',
        'api/rag-pipeline',
        'api/state-graph',
        'api/agents',
        'api/memory',
        'api/retriever',
        'api/vector-store',
        'api/evaluation',
        'api/observability',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/env-vars',
        'reference/errors',
        'reference/troubleshooting',
        'reference/security',
        'reference/production',
      ],
    },
    {
      type: 'category',
      label: 'Cookbook',
      items: [
        'cookbook/intro',
        'cookbook/rag-patterns',
        'cookbook/agent-patterns',
        'cookbook/graph-patterns',
      ],
    },
    'faq',
    'benchmarks',
    'comparison',
    'changelog',
    'roadmap',
  ],
};

export default sidebars;
