import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'architecture',
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/installation' },
      items: ['getting-started/installation', 'getting-started/quickstart'],
    },
    {
      type: 'category',
      label: 'Guides',
      link: { type: 'doc', id: 'guides/index' },
      items: [
        {
          type: 'category',
          label: 'RAG Fundamentals',
          link: { type: 'doc', id: 'guides/rag/index' },
          items: [
            'guides/rag/quickstart-3-lines',
            'guides/rag/pdf-knowledge-base',
            'guides/rag/multi-format-ingestion',
            'guides/rag/chunking-strategies',
            'guides/rag/streaming-rag',
            'guides/rag/rag-with-memory',
            'guides/rag/metadata-filtering',
            'guides/rag/hybrid-bm25-vector',
          ],
        },
        {
          type: 'category',
          label: 'Advanced Retrieval',
          link: { type: 'doc', id: 'guides/retrieval/index' },
          items: [
            'guides/retrieval/rag-fusion',
            'guides/retrieval/graph-rag',
            'guides/retrieval/self-rag',
            'guides/retrieval/parent-document-retriever',
            'guides/retrieval/query-decomposition',
            'guides/retrieval/cross-encoder-reranking',
            'guides/retrieval/adaptive-rag',
          ],
        },
        {
          type: 'category',
          label: 'Agents & Tools',
          link: { type: 'doc', id: 'guides/agents/index' },
          items: [
            'guides/agents/react-research-assistant',
            'guides/agents/custom-tool-creation',
            'guides/agents/web-search-agent',
            'guides/agents/code-execution-agent',
            'guides/agents/sql-database-agent',
            'guides/agents/multi-tool-orchestration',
            'guides/agents/agent-with-guardrails',
            'guides/agents/streaming-agent',
            'guides/agents/structured-output-function-calling',
            'guides/agents/tool-error-handling',
          ],
        },
        {
          type: 'category',
          label: 'Multi-Agent Systems',
          link: { type: 'doc', id: 'guides/multi-agent/index' },
          items: [
            'guides/multi-agent/crew-content-pipeline',
            'guides/multi-agent/supervisor-routing',
            'guides/multi-agent/handoff-chains',
            'guides/multi-agent/a2a-communication',
            'guides/multi-agent/parallel-agent-execution',
          ],
        },
        {
          type: 'category',
          label: 'Graph Workflows',
          link: { type: 'doc', id: 'guides/graph/index' },
          items: [
            'guides/graph/linear-workflow',
            'guides/graph/conditional-routing',
            'guides/graph/fan-out-fan-in',
            'guides/graph/subgraph-composition',
            'guides/graph/checkpointing-resumable',
            'guides/graph/human-in-the-loop',
            'guides/graph/error-recovery',
            'guides/graph/mermaid-visualization',
          ],
        },
        {
          type: 'category',
          label: 'LLM Providers & Optimization',
          link: { type: 'doc', id: 'guides/llms/index' },
          items: [
            'guides/llms/provider-comparison',
            'guides/llms/cost-router',
            'guides/llms/fallback-chain',
            'guides/llms/semantic-caching',
            'guides/llms/structured-output-pydantic',
          ],
        },
        {
          type: 'category',
          label: 'Real-World Integrations',
          link: { type: 'doc', id: 'guides/integrations/index' },
          items: [
            'guides/integrations/github-pr-review-agent',
            'guides/integrations/notion-knowledge-base',
            'guides/integrations/slack-qa-bot',
            'guides/integrations/sql-analytics-agent',
            'guides/integrations/email-triage',
            'guides/integrations/youtube-summarizer',
            'guides/integrations/news-monitoring-dashboard',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: { type: 'doc', id: 'concepts/index' },
      items: [
        'concepts/rag',
        'concepts/agents',
        'concepts/graphs',
        'concepts/embeddings',
      ],
    },
    {
      type: 'category',
      label: 'RAG',
      link: { type: 'doc', id: 'rag/index' },
      items: [
        'rag/pipeline',
        'rag/loaders',
        'rag/splitter',
        'rag/retriever',
        'rag/vector-stores',
        'rag/parsers',
        'rag/prompts',
        'rag/prompt-hub',
      ],
    },
    {
      type: 'category',
      label: 'LLMs',
      link: { type: 'doc', id: 'llms/index' },
      items: [
        'llms/overview',
        'llms/openai',
        'llms/anthropic',
        'llms/ollama',
        'llms/cohere',
        'llms/mistral',
        'llms/gemini',
        'llms/bedrock',
        'llms/azure-openai',
        'llms/groq',
        'llms/deepseek',
        'llms/openrouter',
        'llms/together',
        'llms/fireworks',
        'llms/perplexity',
        'llms/cerebras',
        'llms/vertex-ai',
        'llms/moonshot',
        'llms/zhipu',
        'llms/cloudflare',
        'llms/ai21',
        'llms/databricks',
        'llms/ernie',
        'llms/llamacpp',
        'llms/minimax',
        'llms/aleph-alpha',
        'llms/huggingface',
        'llms/sambanova',
        'llms/xai',
        'llms/novita',
        'llms/writer',
        'llms/lmstudio',
        'llms/gpt4all',
        'llms/vllm',
        'llms/replicate',
        'llms/caching-retries',
        'llms/cost-router',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      link: { type: 'doc', id: 'agents/index' },
      items: [
        'agents/overview',
        'agents/react',
        'agents/function-calling',
        'agents/tools',
        'agents/executor',
        'agents/mcp',
        'agents/cookbook',
        'agents/tool-authoring',
        'agents/streaming-steps',
      ],
    },
    {
      type: 'category',
      label: 'Multi-Agent',
      link: { type: 'doc', id: 'multi-agent/index' },
      items: ['multi-agent/overview', 'multi-agent/a2a'],
    },
    {
      type: 'category',
      label: 'Evaluation',
      link: { type: 'doc', id: 'evaluation/index' },
      items: ['evaluation/overview'],
    },
    {
      type: 'category',
      label: 'Guardrails',
      link: { type: 'doc', id: 'guardrails/index' },
      items: ['guardrails/overview'],
    },
    {
      type: 'category',
      label: 'Observability',
      link: { type: 'doc', id: 'observability/index' },
      items: ['observability/overview', 'observability/cost-tracker', 'observability/audit-log'],
    },
    {
      type: 'category',
      label: 'Multimodal',
      link: { type: 'doc', id: 'multimodal/index' },
      items: ['multimodal/overview'],
    },
    {
      type: 'category',
      label: 'Graph Workflows',
      link: { type: 'doc', id: 'graph/index' },
      items: [
        'graph/overview',
        'graph/state-graph',
        'graph/nodes',
        'graph/edges',
        'graph/compiled-graph',
        'graph/cycles',
        'graph/checkpointing',
        'graph/mermaid',
      ],
    },
    {
      type: 'category',
      label: 'CLI',
      link: { type: 'doc', id: 'cli/index' },
      items: ['cli/overview', 'cli/serve', 'cli/test'],
    },
    'plugins',
    {
      type: 'category',
      label: 'Memory & Tracing',
      link: { type: 'doc', id: 'memory/index' },
      items: ['memory/conversation', 'memory/token-tracer'],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      link: { type: 'doc', id: 'how-to/index' },
      items: [
        'how-to/index',
        'how-to/streaming',
        'how-to/custom-llm-provider',
        'how-to/custom-tools',
        'how-to/custom-retrievers',
        'how-to/memory',
        'how-to/error-handling',
        'how-to/testing',
        'how-to/production',
        'how-to/migrate-from-langchain',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: { type: 'doc', id: 'api/index' },
      items: [
        'api/llm',
        'api/rag-pipeline',
        'api/state-graph',
        'api/agents',
        'api/memory',
        'api/retriever',
        'api/vector-store',
        'api/evaluation',
        'api/observability',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'doc', id: 'reference/index' },
      items: [
        'reference/env-vars',
        'reference/errors',
        'reference/troubleshooting',
        'reference/security',
        'reference/production',
      ],
    },
    {
      type: 'category',
      label: 'Patterns',
      link: { type: 'doc', id: 'patterns/index' },
      items: [
        'patterns/rag-patterns',
        'patterns/agent-patterns',
        'patterns/graph-patterns',
      ],
    },
    {
      type: 'category',
      label: 'EvalCI',
      link: { type: 'doc', id: 'evalci/index' },
      items: [
        'evalci/overview',
        'evalci/quickstart',
        'evalci/writing-evals',
        'evalci/action-reference',
        'evalci/examples',
        'evalci/troubleshooting',
      ],
    },
    'faq',
    'benchmarks',
    'comparison',
    'changelog',
  ],
};

export default sidebars;
